[tool.poetry]
name = "parrot"
version = "3.2.0"
description = ""
authors = ["Nate <14845347+garlic-os@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = "^2.3.2"
jishaku = "^2.5.1"
markovify = "^0.9.4"
Pillow = "^10.0.0"
PyYAML = "^6.0.1"
asyncio-atexit = "^1.0.1"
async-lru = "^2.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
